// <auto-generated />
using System;
using ItemOrganizer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItemOrganizer.Infrastructure.Migrations
{
    [DbContext(typeof(ItemOrganizerDbContext))]
    partial class ItemOrganizerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItemOrganizer.Domain.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application_version");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancellation_requested_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<Guid?>("ConfirmedContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_container_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_attempt_count");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("OwnerObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_object_id");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<string[]>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("warnings");

                    b.HasKey("Id")
                        .HasName("pk_analyses");

                    b.HasAlternateKey("Id", "TenantId", "OwnerObjectId")
                        .HasName("ak_analyses_id_tenant_id_owner_object_id");

                    b.HasIndex("PhotoId", "Status")
                        .HasDatabaseName("ix_analyses_photo_id_status");

                    b.HasIndex("TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_analyses_tenant_id_owner_object_id");

                    b.HasIndex("ConfirmedContainerId", "TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_analyses_confirmed_container_id_tenant_id_owner_object_id");

                    b.HasIndex("PhotoId", "TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_analyses_photo_id_tenant_id_owner_object_id");

                    b.ToTable("analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_analyses_attempt_count", "delivery_attempt_count BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_analyses_owner", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND owner_object_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_analyses_terminal_timestamp", "(status IN ('Completed', 'Failed') AND completed_at IS NOT NULL) OR (status = 'Cancelled' AND cancelled_at IS NOT NULL) OR (status IN ('Queued', 'Running') AND completed_at IS NULL AND cancelled_at IS NULL)");

                            t.HasCheckConstraint("ck_analyses_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("ItemOrganizer.Domain.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<Guid>("OwnerObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_object_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasAlternateKey("Id", "TenantId", "OwnerObjectId")
                        .HasName("ak_idempotency_records_id_tenant_id_owner_object_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_idempotency_records_tenant_id_owner_object_id");

                    b.HasIndex("TenantId", "OwnerObjectId", "Operation", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_tenant_id_owner_object_id_operation_key");

                    b.ToTable("idempotency_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_idempotency_records_owner", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND owner_object_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_idempotency_records_timestamps", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_idempotency_result", "(status = 'InProgress' AND resource_id IS NULL AND error_code IS NULL) OR (status = 'Completed' AND resource_id IS NOT NULL AND resource_type IS NOT NULL AND error_code IS NULL) OR (status = 'Failed' AND resource_id IS NULL AND error_code IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ItemOrganizer.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("deduplication_key");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_category");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OwnerObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_object_id");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasAlternateKey("Id", "TenantId", "OwnerObjectId")
                        .HasName("ak_items_id_tenant_id_owner_object_id");

                    b.HasIndex("AnalysisId", "DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_items_analysis_id_deduplication_key");

                    b.HasIndex("TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_items_tenant_id_owner_object_id");

                    b.HasIndex("AnalysisId", "TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_items_analysis_id_tenant_id_owner_object_id");

                    b.HasIndex("PhotoId", "TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_items_photo_id_tenant_id_owner_object_id");

                    b.HasIndex("TenantId", "OwnerObjectId", "NormalizedName")
                        .HasDatabaseName("ix_items_tenant_id_owner_object_id_normalized_name");

                    b.ToTable("items", null, t =>
                        {
                            t.HasCheckConstraint("ck_items_confidence", "confidence BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_items_deleted_at", "deleted_at IS NULL OR deleted_at >= created_at");

                            t.HasCheckConstraint("ck_items_owner", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND owner_object_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_items_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("ItemOrganizer.Domain.ItemAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("OwnerObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_object_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SuggestedContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_container_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_item_assignments");

                    b.HasAlternateKey("Id", "TenantId", "OwnerObjectId")
                        .HasName("ak_item_assignments_id_tenant_id_owner_object_id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_assignments_item_id");

                    b.HasIndex("TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_item_assignments_tenant_id_owner_object_id");

                    b.HasIndex("ContainerId", "TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_item_assignments_container_id_tenant_id_owner_object_id");

                    b.HasIndex("ItemId", "TenantId", "OwnerObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_assignments_item_id_tenant_id_owner_object_id");

                    b.HasIndex("SuggestedContainerId", "TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_item_assignments_suggested_container_id_tenant_id_owner_obj");

                    b.ToTable("item_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_assignments_owner", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND owner_object_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_item_assignments_state", "(status = 'Unassigned' AND source = 'None' AND container_id IS NULL AND suggested_container_id IS NULL) OR (status = 'Suggested' AND source = 'AiSuggestion' AND container_id IS NULL AND suggested_container_id IS NOT NULL) OR (status = 'Confirmed' AND source IN ('User', 'ConvenienceWorkflow') AND container_id IS NOT NULL AND suggested_container_id IS NULL)");

                            t.HasCheckConstraint("ck_item_assignments_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("ItemOrganizer.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_error_code");

                    b.Property<Guid>("OwnerObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_object_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasAlternateKey("Id", "TenantId", "OwnerObjectId")
                        .HasName("ak_outbox_messages_id_tenant_id_owner_object_id");

                    b.HasIndex("AnalysisId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_analysis_id");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_outbox_messages_status_available_at");

                    b.HasIndex("TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id_owner_object_id");

                    b.HasIndex("AnalysisId", "TenantId", "OwnerObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_analysis_id_tenant_id_owner_object_id");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_messages_owner", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND owner_object_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_outbox_messages_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("ItemOrganizer.Domain.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("blob_name");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint")
                        .HasColumnName("content_length");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("OwnerObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_object_id");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retain_until");

                    b.Property<string>("RetentionState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("retention_state");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasAlternateKey("Id", "TenantId", "OwnerObjectId")
                        .HasName("ak_photos_id_tenant_id_owner_object_id");

                    b.HasIndex("RetentionState", "RetainUntil")
                        .HasDatabaseName("ix_photos_retention_state_retain_until");

                    b.HasIndex("TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_photos_tenant_id_owner_object_id");

                    b.HasIndex("TenantId", "OwnerObjectId", "Sha256")
                        .HasDatabaseName("ix_photos_tenant_id_owner_object_id_sha256");

                    b.ToTable("photos", null, t =>
                        {
                            t.HasCheckConstraint("ck_photos_content_length", "content_length > 0 AND content_length <= 10485760");

                            t.HasCheckConstraint("ck_photos_dimensions", "width BETWEEN 512 AND 8000 AND height BETWEEN 512 AND 8000");

                            t.HasCheckConstraint("ck_photos_owner", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND owner_object_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_photos_retention", "retain_until >= created_at");

                            t.HasCheckConstraint("ck_photos_sha256", "sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_photos_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("ItemOrganizer.Domain.StorageContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("OwnerObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_object_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_containers");

                    b.HasAlternateKey("Id", "TenantId", "OwnerObjectId")
                        .HasName("ak_containers_id_tenant_id_owner_object_id");

                    b.HasIndex("TenantId", "OwnerObjectId")
                        .HasDatabaseName("ix_containers_tenant_id_owner_object_id");

                    b.HasIndex("TenantId", "OwnerObjectId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_containers_tenant_id_owner_object_id_normalized_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("containers", null, t =>
                        {
                            t.HasCheckConstraint("ck_containers_deleted_at", "deleted_at IS NULL OR deleted_at >= created_at");

                            t.HasCheckConstraint("ck_containers_owner", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND owner_object_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_containers_timestamps", "updated_at >= created_at");
                        });
                });

            modelBuilder.Entity("ItemOrganizer.Domain.Analysis", b =>
                {
                    b.HasOne("ItemOrganizer.Domain.StorageContainer", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedContainerId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_analyses_containers_confirmed_container_id_tenant_id_owner_");

                    b.HasOne("ItemOrganizer.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotoId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_analyses_photos_photo_id_tenant_id_owner_object_id");
                });

            modelBuilder.Entity("ItemOrganizer.Domain.Item", b =>
                {
                    b.HasOne("ItemOrganizer.Domain.Analysis", null)
                        .WithMany()
                        .HasForeignKey("AnalysisId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_analyses_analysis_id_tenant_id_owner_object_id");

                    b.HasOne("ItemOrganizer.Domain.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotoId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_photos_photo_id_tenant_id_owner_object_id");
                });

            modelBuilder.Entity("ItemOrganizer.Domain.ItemAssignment", b =>
                {
                    b.HasOne("ItemOrganizer.Domain.StorageContainer", null)
                        .WithMany()
                        .HasForeignKey("ContainerId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_item_assignments_containers_container_id_tenant_id_owner_ob");

                    b.HasOne("ItemOrganizer.Domain.Item", null)
                        .WithOne("Assignment")
                        .HasForeignKey("ItemOrganizer.Domain.ItemAssignment", "ItemId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("ItemOrganizer.Domain.Item", "Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_assignments_items_item_id_tenant_id_owner_object_id");

                    b.HasOne("ItemOrganizer.Domain.StorageContainer", null)
                        .WithMany()
                        .HasForeignKey("SuggestedContainerId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_item_assignments_containers_suggested_container_id_tenant_i");
                });

            modelBuilder.Entity("ItemOrganizer.Domain.OutboxMessage", b =>
                {
                    b.HasOne("ItemOrganizer.Domain.Analysis", null)
                        .WithOne()
                        .HasForeignKey("ItemOrganizer.Domain.OutboxMessage", "AnalysisId", "TenantId", "OwnerObjectId")
                        .HasPrincipalKey("ItemOrganizer.Domain.Analysis", "Id", "TenantId", "OwnerObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_messages_analyses_analysis_id_tenant_id_owner_object");
                });

            modelBuilder.Entity("ItemOrganizer.Domain.Item", b =>
                {
                    b.Navigation("Assignment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
